version: '3.5'

services:
  db:
    image: postgres:11.6
    container_name: 'cric-fantacy-db'
    networks:
      - 'cric-fantacy-api'
    restart: always
    env_file:
      - src/conf/env/.env
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  api:
    container_name: cric-fantacy-api
    env_file:
      - src/conf/env/.env
    build: .
    networks:
      - cric-fantacy-api
    ports:
      - '8000:8000'
    depends_on:
      - db
    entrypoint:
      - ./entrypoint.sh
      - npm
      - run
      - start

volumes:
  postgres: ~

networks:
  cric-fantacy-api:
    name: cric-fantacy-network
