export const ISLUN = [
    {
        "Id": 15388,
        "fn": "Amad Butt",
        "n": "Amad Butt",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 9902
    },
    {
        "Id": 15386,
        "fn": "Asif Ali",
        "n": "Asif Ali",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 9565
    },
    {
        "Id": 15397,
        "fn": "Cameron Delport",
        "n": "Cameron Delport",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 9719
    },
    {
        "Id": 12299,
        "fn": "Chadwick Antonio Kirkpatrick Walton",
        "n": "Chadwick Walton",
        "nn": "",
        "bts": false,
        "bs": "Wicketkeeper batsman",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 1988
    },
    {
        "Id": 15633,
        "fn": "Fahim Ashraf",
        "n": "Faheem Ashraf",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 11265
    },
    {
        "Id": 15387,
        "fn": "Hussain Talat",
        "n": "Hussain Talat",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 9804
    },
    {
        "Id": 11208,
        "fn": "Ian Ronald Bell",
        "n": "Ian Bell",
        "nn": "",
        "bts": false,
        "bs": "Top-order batsman",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 385
    },
    {
        "Id": 12594,
        "fn": "Luke Ronchi",
        "n": "Luke Ronchi",
        "nn": "",
        "bts": false,
        "bs": "Wicketkeeper batsman",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 1396
    },
    {
        "Id": 13044,
        "fn": "Mohammad Sami",
        "n": "Mohammad Sami",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 31
    },
    {
        "Id": 15970,
        "fn": "Muhammad Musa",
        "n": "Muhammad Musa",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 12156
    },
    {
        "Id": 15910,
        "fn": "Nasir Nawaz",
        "n": "Nasir Nawaz",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 12137
    },
    {
        "Id": 18690,
        "fn": "Philip Salt",
        "n": "Philip Salt",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 10479
    },
    {
        "Id": 17306,
        "fn": "Rizwan Hussain",
        "n": "Rizwan Hussain",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 14562
    },
    {
        "Id": 14186,
        "fn": "Rumman Raees Khan",
        "n": "Rumman Raees",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 10861
    },
    {
        "Id": 15875,
        "fn": "Sahibzada Farhan",
        "n": "Sahibzada Farhan",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 13625
    },
    {
        "Id": 11234,
        "fn": "Samit Rohit Patel",
        "n": "Samit Patel",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 1414
    },
    {
        "Id": 15390,
        "fn": "Shadab Khan",
        "n": "Shadab Khan",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 11186
    },
    {
        "Id": 15891,
        "fn": "Waqas Maqsood",
        "n": "Waqas Maqsood",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 9557
    },
    {
        "Id": 12002,
        "fn": "Wayne Dillon Parnell",
        "n": "Wayne Parnell",
        "nn": "",
        "bts": false,
        "bs": "Bowler",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 1692
    },
    {
        "Id": 13734,
        "fn": "Zafar Gohar Khan",
        "n": "Zafar Gohar",
        "nn": "",
        "bts": false,
        "bs": "Left-hand bat",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8567
    },
    {
        "Id": 15840,
        "fn": "Zahir Khan",
        "n": "Zahir Khan",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 10828
    },
    {
        "Id": 11252,
        "fn": "Alexander Daniel Hales",
        "n": "Alex Hales",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 6734
    }
];

export const KK = [
    {
        "Id": 13732,
        "fn": "Aamer Yamin",
        "n": "Aamer Yamin",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 10618
    },
    {
        "Id": 15955,
        "fn": "Aaron Summers",
        "n": "Aaron Summers",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 13387
    },
    {
        "Id": 15395,
        "fn": "Abrar Ahmed",
        "n": "Abrar Ahmed",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 12555
    },
    {
        "Id": 18734,
        "fn": "Ali Imran",
        "n": "Ali Imran",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 14372
    },
    {
        "Id": 14179,
        "fn": "Awais Zia",
        "n": "Awais Zia",
        "nn": "",
        "bts": false,
        "bs": "Left-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8249
    },
    {
        "Id": 13099,
        "fn": "Mohammad Babar Azam",
        "n": "Babar Azam",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8359
    },
    {
        "Id": 14145,
        "fn": "Ben Robert Dunk",
        "n": "Ben Dunk",
        "nn": "",
        "bts": false,
        "bs": "Left-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8142
    },
    {
        "Id": 13533,
        "fn": "Colin Alexander Ingram",
        "n": "Colin Ingram",
        "nn": "",
        "bts": false,
        "bs": "Top-order batsman",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 7664
    },
    {
        "Id": 12585,
        "fn": "Colin Munro",
        "n": "Colin Munro",
        "nn": "",
        "bts": false,
        "bs": "Left-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8085
    },
    {
        "Id": 13098,
        "fn": "Iftikhar Ahmed",
        "n": "Iftikhar Ahmed",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 10799
    },
    {
        "Id": 13731,
        "fn": "Syed Imad Wasim",
        "n": "Imad Wasim",
        "nn": "",
        "bts": false,
        "bs": "Left-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 10408
    },
    {
        "Id": 15877,
        "fn": "Jaahid Ali",
        "n": "Jaahid Ali",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8365
    },
    {
        "Id": 15487,
        "fn": "Liam Livingstone",
        "n": "Liam Livingstone",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 10045
    },
    {
        "Id": 13071,
        "fn": "Mohammad Amir",
        "n": "Mohammad Amir",
        "nn": "",
        "bts": false,
        "bs": "Bowler",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 1917
    },
    {
        "Id": 13729,
        "fn": "Mohammad Rizwan",
        "n": "Mohammad Rizwan",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 9468
    },
    {
        "Id": 11220,
        "fn": "Ravinder Singh Bopara",
        "n": "Ravi Bopara",
        "nn": "",
        "bts": false,
        "bs": "Middle-order batsman",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 571
    },
    {
        "Id": 13328,
        "fn": "Sikandar Raza Butt",
        "n": "Sikandar Raza",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 9354
    },
    {
        "Id": 13068,
        "fn": "Sohail Khan",
        "n": "Sohail Khan",
        "nn": "",
        "bts": false,
        "bs": "Bowler",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 1120
    },
    {
        "Id": 18832,
        "fn": "Umer Khan",
        "n": "Umer Khan",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 12161
    },
    {
        "Id": 14233,
        "fn": "Usama Mir",
        "n": "Usama Mir",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 11318
    },
    {
        "Id": 14181,
        "fn": "Usman Khan Shinwari",
        "n": "Usman Shinwari",
        "nn": "",
        "bts": false,
        "bs": "Bowler",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 9698
    }
];

export const LQ = [
    {
        "Id": 11991,
        "fn": "Abraham Benjamin de Villiers",
        "n": "AB de Villiers",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 370
    },
    {
        "Id": 15887,
        "fn": "Agha Salman",
        "n": "Agha Salman",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 10101
    },
    {
        "Id": 13084,
        "fn": "Aizaz Bin Ilyas Cheema",
        "n": "Aizaz Cheema",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8065
    },
    {
        "Id": 18485,
        "fn": "Anton Paul Devcich",
        "n": "Anton Devcich",
        "nn": "A.P.",
        "bts": null,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 9065
    },
    {
        "Id": 13302,
        "fn": "Brendan Ross Murray Taylor",
        "n": "Brendan Taylor",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 180
    },
    {
        "Id": 12325,
        "fn": "Carlos Ricardo Brathwaite",
        "n": "Carlos Brathwaite",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8110
    },
    {
        "Id": 12588,
        "fn": "Corey James Anderson",
        "n": "Corey Anderson",
        "nn": "",
        "bts": false,
        "bs": "Left-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8982
    },
    {
        "Id": 13540,
        "fn": "David Wiese",
        "n": "David Wiese",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8589
    },
    {
        "Id": 15393,
        "fn": "Fakhar Zaman",
        "n": "Fakhar Zaman",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 10863
    },
    {
        "Id": 15872,
        "fn": "Gauhar Ali",
        "n": "Gauhar Ali",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 14560
    },
    {
        "Id": 12020,
        "fn": "GC Viljoen",
        "n": "Hardus Viljoen",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 9493
    },
    {
        "Id": 18760,
        "fn": "Haris Rauf",
        "n": "Haris Rauf",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 14561
    },
    {
        "Id": 13724,
        "fn": "Haris Sohail",
        "n": "Haris Sohail",
        "nn": "",
        "bts": false,
        "bs": "Left-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8299
    },
    {
        "Id": 15405,
        "fn": "Hasan Khan",
        "n": "Hassan Khan",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 0
    },
    {
        "Id": 13050,
        "fn": "Mohammad Hafeez",
        "n": "Mohammad Hafeez",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 360
    },
    {
        "Id": 15892,
        "fn": "Mohammad Imran",
        "n": "Mohammad Imran",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 14546
    },
    {
        "Id": 13088,
        "fn": "Rahat Ali",
        "n": "Rahat Ali",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8301
    },
    {
        "Id": 13850,
        "fn": "Ryan Neil ten Doeschate",
        "n": "Ryan ten Doeschate",
        "nn": "",
        "bts": false,
        "bs": "Allrounder",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 640
    },
    {
        "Id": 15914,
        "fn": "Saad Ali",
        "n": "Saad Ali",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Pakistan",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8368
    },
    {
        "Id": 13055,
        "fn": "Salman Butt",
        "n": "Salman Butt",
        "nn": "",
        "bts": false,
        "bs": "Left-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 143
    },
    {
        "Id": 17241,
        "fn": "Sandeep Lamichhane",
        "n": "Sandeep Lamichhane",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 11158
    },
    {
        "Id": 15827,
        "fn": "Shaheen Afridi",
        "n": "Shaheen Afridi",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 12160
    },
    {
        "Id": 15908,
        "fn": "Sohail Akhtar",
        "n": "Sohail Akhtar",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 13623
    },
    {
        "Id": 15912,
        "fn": "Umair Masood",
        "n": "Umair Masood",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 11194
    },
    {
        "Id": 13096,
        "fn": "Yasir Shah",
        "n": "Yasir Shah",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8064
    },
    {
        "Id": 14269,
        "fn": "Riki Wessels",
        "n": "Riki Wessels",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 7987
    },
    {
        "Id": 13238,
        "fn": "Downdegedara Asela Sampath Gunaratne",
        "n": "Asela Gunaratne",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 10154
    }
];

export const PZ = [
    {
        "Id": 13561,
        "fn": "Andre David Stephon Fletcher",
        "n": "Andre Fletcher",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 1394
    },
    {
        "Id": 11246,
        "fn": "Christopher James Jordan",
        "n": "Chris Jordan",
        "nn": "",
        "bts": false,
        "bs": "Bowler",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 6532
    },
    {
        "Id": 12285,
        "fn": "Darren Julius Garvey Sammy",
        "n": "Darren Sammy",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 253
    },
    {
        "Id": 14241,
        "fn": "Dawid Malan",
        "n": "Dawid Malan",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 6660
    },
    {
        "Id": 13735,
        "fn": "Hasan Ali",
        "n": "Hasan Ali",
        "nn": "",
        "bts": true,
        "bs": "Right-arm medium-fast",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 11320
    },
    {
        "Id": 17263,
        "fn": "Ibtisam Sheikh",
        "n": "Ibtisam Sheikh",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 13620
    },
    {
        "Id": 15819,
        "fn": "Imam-ul-Haq",
        "n": "Imam-ul-Haq",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8364
    },
    {
        "Id": 18763,
        "fn": "Jamal Anwar",
        "n": "Jamal Anwar",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 14544
    },
    {
        "Id": 13049,
        "fn": "Kamran Akmal",
        "n": "Kamran Akmal",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 77
    },
    {
        "Id": 15889,
        "fn": "Khalid Usman",
        "n": "Khalid Usman",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 13622
    },
    {
        "Id": 13558,
        "fn": "Kieron Adrian Pollard",
        "n": "Kieron Pollard",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 657
    },
    {
        "Id": 13464,
        "fn": "Liam Andrew Dawson",
        "n": "Liam Dawson",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 6639
    },
    {
        "Id": 13043,
        "fn": "Misbah-ul-Haq Khan Niazi",
        "n": "Misbah-ul-Haq",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 274
    },
    {
        "Id": 15534,
        "fn": "Nabi Gul",
        "n": "Nabi Gul",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 12715
    },
    {
        "Id": 15897,
        "fn": "Sameen Gul",
        "n": "Sameen Gul",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 11193
    },
    {
        "Id": 18846,
        "fn": "Samiullah",
        "n": "Samiullah",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 0
    },
    {
        "Id": 13725,
        "fn": "Sohaib Maqsood",
        "n": "Sohaib Maqsood",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 9524
    },
    {
        "Id": 15916,
        "fn": "Umaid Asif",
        "n": "Umaid Asif",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8581
    },
    {
        "Id": 13077,
        "fn": "Umar Amin",
        "n": "Umar Amin",
        "nn": "",
        "bts": false,
        "bs": "Left-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 1740
    },
    {
        "Id": 13079,
        "fn": "Wahab Riaz",
        "n": "Wahab Riaz",
        "nn": "",
        "bts": false,
        "bs": "Bowler",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 1051
    },
    {
        "Id": 18764,
        "fn": "Wayne Madsen",
        "n": "Wayne Madsen",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 6808
    },
    {
        "Id": 12292,
        "fn": "Lendl Mark Platter Simmons",
        "n": "Lendl Simmons",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 599
    },
    {
        "Id": 14137,
        "fn": "Tymal Solomon Mills",
        "n": "Tymal Mills",
        "nn": "",
        "bts": true,
        "bs": "Left-arm fast",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 7860
    }
];

export const QG = [
    {
        "Id": 13093,
        "fn": "Ahmed Shehzad",
        "n": "Ahmed Shehzad",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 1787
    },
    {
        "Id": 15457,
        "fn": "Ahsan Ali",
        "n": "Ahsan Ali",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 12702
    },
    {
        "Id": 13726,
        "fn": "Anwar Ali",
        "n": "Anwar Ali",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 1052
    },
    {
        "Id": 18851,
        "fn": "Azam Khan",
        "n": "Azam Khan",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 14558
    },
    {
        "Id": 15880,
        "fn": "Danish Aziz",
        "n": "Danish Aziz",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 13666
    },
    {
        "Id": 12275,
        "fn": "Dwayne John Bravo",
        "n": "Dwayne Bravo",
        "nn": "",
        "bts": false,
        "bs": "Allrounder",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 242
    },
    {
        "Id": 12274,
        "fn": "Dwayne Romel Smith",
        "n": "Dwayne Smith",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 255
    },
    {
        "Id": 13495,
        "fn": "Fawad Ahmed",
        "n": "Fawad Ahmed",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8969
    },
    {
        "Id": 15399,
        "fn": "Ghulam Mudassar",
        "n": "Ghulam Mudassar",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 0
    },
    {
        "Id": 13459,
        "fn": "Harry Frederick Gurney",
        "n": "Harry Gurney",
        "nn": "",
        "bts": false,
        "bs": "Bowler",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 6496
    },
    {
        "Id": 18762,
        "fn": "Jalat Khan",
        "n": "Jalat Khan",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 14559
    },
    {
        "Id": 18853,
        "fn": "Max Waller",
        "n": "Max Waller",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 2266
    },
    {
        "Id": 14273,
        "fn": "Mohammad Asghar",
        "n": "Mohammad Asghar",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 0
    },
    {
        "Id": 18852,
        "fn": "Mohammad Hasnain",
        "n": "Mohammad Hasnain",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 14248
    },
    {
        "Id": 18547,
        "fn": "Mohammad Irfan",
        "n": "Mohammad Irfan",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 12606
    },
    {
        "Id": 13100,
        "fn": "Mohammad Nawaz",
        "n": "Mohammad Nawaz",
        "nn": "",
        "bts": false,
        "bs": "Left-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8367
    },
    {
        "Id": 18761,
        "fn": "Naseem Shah",
        "n": "Naseem Shah",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 14247
    },
    {
        "Id": 13538,
        "fn": "Rilee Roscoe Rossouw",
        "n": "Rilee Rossouw",
        "nn": "",
        "bts": false,
        "bs": "Left-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 2244
    },
    {
        "Id": 13075,
        "fn": "Sarfraz Ahmed",
        "n": "Sarfaraz Ahmed",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 881
    },
    {
        "Id": 17189,
        "fn": "Saud Shakeel",
        "n": "Saud Shakeel",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 9812
    },
    {
        "Id": 11643,
        "fn": "Shane Robert Watson",
        "n": "Shane Watson",
        "nn": "",
        "bts": false,
        "bs": "Allrounder",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 158
    },
    {
        "Id": 13065,
        "fn": "Sohail Tanvir",
        "n": "Sohail Tanvir",
        "nn": "",
        "bts": false,
        "bs": "Left-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 859
    },
    {
        "Id": 12314,
        "fn": "Sunil Philip Narine",
        "n": "Sunil Narine",
        "nn": "",
        "bts": false,
        "bs": "Left-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 2276
    },
    {
        "Id": 13074,
        "fn": "Umar Akmal",
        "n": "Umar Akmal",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 1992
    }
];

export const MS = [
    {
        "Id": 15924,
        "fn": "Ali Shafiq",
        "n": "Ali Shafiq",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 14359
    },
    {
        "Id": 12307,
        "fn": "Andre Dwayne Russell",
        "n": "Andre Russell",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 7736
    },
    {
        "Id": 18484,
        "fn": "Christopher James Green",
        "n": "Chris Green",
        "nn": "C.J.",
        "bts": null,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 10162
    },
    {
        "Id": 13490,
        "fn": "Daniel Trevor Christian",
        "n": "Daniel Christian",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 6283
    },
    {
        "Id": 13721,
        "fn": "Hammad Azam",
        "n": "Hammad Azam",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 6272
    },
    {
        "Id": 11253,
        "fn": "James Michael Vince",
        "n": "James Vince",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 6642
    },
    {
        "Id": 13568,
        "fn": "Johnson Charles",
        "n": "Johnson Charles",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8101
    },
    {
        "Id": 13085,
        "fn": "Mohammad Junaid Khan",
        "n": "Junaid Khan",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 7900
    },
    {
        "Id": 18510,
        "fn": "Laurie Evans",
        "n": "Laurie Evans",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 6531
    },
    {
        "Id": 15628,
        "fn": "Mohammad Abbas",
        "n": "Mohammad Abbas",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 11298
    },
    {
        "Id": 18786,
        "fn": "Mohammad Ilyas",
        "n": "Mohammad Ilyas",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 12714
    },
    {
        "Id": 18785,
        "fn": "Mohammad Junaid",
        "n": "Mohammad Junaid",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 0
    },
    {
        "Id": 18784,
        "fn": "Nauman Ali",
        "n": "Nauman Ali",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 14545
    },
    {
        "Id": 13030,
        "fn": "Sahibzada Mohammad Shahid Khan Afridi",
        "n": "Shahid Afridi",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "شاہد آفریدی",
        "ine": false,
        "tids": null,
        "cbId": 142
    },
    {
        "Id": 14180,
        "fn": "Shakeel Ansar",
        "n": "Shakeel Ansar",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8300
    },
    {
        "Id": 13091,
        "fn": "Shan Masood Khan",
        "n": "Shan Masood",
        "nn": "",
        "bts": false,
        "bs": "Shaani",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 9545
    },
    {
        "Id": 13046,
        "fn": "Shoaib Malik",
        "n": "Shoaib Malik",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 33
    },
    {
        "Id": 18686,
        "fn": "Tom Moores",
        "n": "Tom Moores",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 10921
    },
    {
        "Id": 17264,
        "fn": "Umar Siddiq",
        "n": "Umar Siddiq",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 10089
    },
    {
        "Id": 13089,
        "fn": "Mohammad Irfan",
        "n": "Muhammad Irfan",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 7621
    },
    {
        "Id": 15885,
        "fn": "Mohammad Irfan",
        "n": "Mohammad Irfan Khan",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 0
    }
];