export const MatchSchedule = [
    {
        "mid": 5758,
        "mt": "3",
        "imt": 3,
        "mh": "Match 1",
        "md": "02/14/2019 00:00:00",
        "mti": "5:45 PM",
        "ml": "Dubai",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "ISLU won by 5 wickets",
        "umr": "",
        "t1i": "58",
        "t1tt": 0,
        "t1t": "Islamabad United",
        "t1n": "ISLU",
        "t1s": "177/5",
        "t1o": "19.2 ovs",
        "t1i1s": "177/5",
        "t1i2s": "",
        "t1i1o": "19.2 ovs",
        "t1i2o": "",
        "t2i": "60",
        "t2tt": 0,
        "t2t": "Lahore Qalandars",
        "t2n": "LQ",
        "t2s": "171/8",
        "t2o": "20 ovs",
        "t2i1s": "171/8",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "پہلا میچ",
        "uv": "دوبئی",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "islamabad-united-vs-lahore-qalandars-match-1-2019",
        "mVnu": {
            "id": 53,
            "oid": 262,
            "t": "Dubai International Cricket Stadium",
            "ut": "",
            "ci": "Dubai",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5759,
        "mt": "3",
        "imt": 3,
        "mh": "Match 2",
        "md": "02/15/2019 00:00:00",
        "mti": "11:30 AM",
        "ml": "Dubai",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "KK won by 7 runs",
        "umr": "",
        "t1i": "104",
        "t1tt": 0,
        "t1t": "Multan Sultans",
        "t1n": "MS",
        "t1s": "176/9",
        "t1o": "20 ovs",
        "t1i1s": "176/9",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "59",
        "t2tt": 0,
        "t2t": "Karachi Kings",
        "t2n": "KK",
        "t2s": "183/6",
        "t2o": "20 ovs",
        "t2i1s": "183/6",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "multan-sultans-vs-karachi-kings-match-2-2019",
        "mVnu": {
            "id": 53,
            "oid": 262,
            "t": "Dubai International Cricket Stadium",
            "ut": "",
            "ci": "Dubai",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5760,
        "mt": "3",
        "imt": 3,
        "mh": "Match 3",
        "md": "02/15/2019 00:00:00",
        "mti": "4:00 PM",
        "ml": "Dubai",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "QG won by 6 wickets",
        "umr": "",
        "t1i": "61",
        "t1tt": 0,
        "t1t": "Peshawar Zalmi",
        "t1n": "PZ",
        "t1s": "155/4",
        "t1o": "20 ovs",
        "t1i1s": "155/4",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "62",
        "t2tt": 0,
        "t2t": "Quetta Gladiators",
        "t2n": "QG",
        "t2s": "161/4",
        "t2o": "19.4 ovs",
        "t2i1s": "161/4",
        "t2i2s": "",
        "t2i1o": "19.4 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "peshawar-zalmi-vs-quetta-gladiators-match-3-2019",
        "mVnu": {
            "id": 53,
            "oid": 262,
            "t": "Dubai International Cricket Stadium",
            "ut": "",
            "ci": "Dubai",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5761,
        "mt": "3",
        "imt": 3,
        "mh": "Match 4",
        "md": "02/16/2019 00:00:00",
        "mti": "11:30 AM",
        "ml": "Dubai",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "MS won by 5 wickets",
        "umr": "",
        "t1i": "58",
        "t1tt": 0,
        "t1t": "Islamabad United",
        "t1n": "ISLU",
        "t1s": "125/7",
        "t1o": "20 ovs",
        "t1i1s": "125/7",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "104",
        "t2tt": 0,
        "t2t": "Multan Sultans",
        "t2n": "MS",
        "t2s": "126/5",
        "t2o": "18.4 ovs",
        "t2i1s": "126/5",
        "t2i2s": "",
        "t2i1o": "18.4 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "islamabad-united-vs-multan-sultans-match-4-2019",
        "mVnu": {
            "id": 53,
            "oid": 262,
            "t": "Dubai International Cricket Stadium",
            "ut": "",
            "ci": "Dubai",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5762,
        "mt": "3",
        "imt": 3,
        "mh": "Match 5",
        "md": "02/16/2019 00:00:00",
        "mti": "4:00 PM",
        "ml": "Dubai",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "LQ won by 22 runs",
        "umr": "",
        "t1i": "60",
        "t1tt": 0,
        "t1t": "Lahore Qalandars",
        "t1n": "LQ",
        "t1s": "138/6",
        "t1o": "20 ovs",
        "t1i1s": "138/6",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "59",
        "t2tt": 0,
        "t2t": "Karachi Kings",
        "t2n": "KK",
        "t2s": "116/10",
        "t2o": "19.5 ovs",
        "t2i1s": "116/10",
        "t2i2s": "",
        "t2i1o": "19.5 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "lahore-qalandars-vs-karachi-kings-match-5-2019",
        "mVnu": {
            "id": 53,
            "oid": 262,
            "t": "Dubai International Cricket Stadium",
            "ut": "",
            "ci": "Dubai",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5763,
        "mt": "3",
        "imt": 3,
        "mh": "Match 6",
        "md": "02/17/2019 00:00:00",
        "mti": "11:30 AM",
        "ml": "Dubai",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "QG won by 7 wickets",
        "umr": "",
        "t1i": "58",
        "t1tt": 0,
        "t1t": "Islamabad United",
        "t1n": "ISLU",
        "t1s": "157/8",
        "t1o": "20 ovs",
        "t1i1s": "157/8",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "62",
        "t2tt": 0,
        "t2t": "Quetta Gladiators",
        "t2n": "QG",
        "t2s": "161/3",
        "t2o": "18.2 ovs",
        "t2i1s": "161/3",
        "t2i2s": "",
        "t2i1o": "18.2 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "islamabad-united-vs-quetta-gladiators-match-6-2019",
        "mVnu": {
            "id": 53,
            "oid": 262,
            "t": "Dubai International Cricket Stadium",
            "ut": "",
            "ci": "Dubai",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5764,
        "mt": "3",
        "imt": 3,
        "mh": "Match 7",
        "md": "02/17/2019 00:00:00",
        "mti": "4:00 PM",
        "ml": "Dubai",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "PZ won by 7 wickets",
        "umr": "",
        "t1i": "61",
        "t1tt": 0,
        "t1t": "Peshawar Zalmi",
        "t1n": "PZ",
        "t1s": "81/3",
        "t1o": "10.1 ovs",
        "t1i1s": "81/3",
        "t1i2s": "",
        "t1i1o": "10.1 ovs",
        "t1i2o": "",
        "t2i": "60",
        "t2tt": 0,
        "t2t": "Lahore Qalandars",
        "t2n": "LQ",
        "t2s": "78/10",
        "t2o": "15.1 ovs",
        "t2i1s": "78/10",
        "t2i2s": "",
        "t2i1o": "15.1 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "peshawar-zalmi-vs-lahore-qalandars-match-7-2019",
        "mVnu": {
            "id": 53,
            "oid": 262,
            "t": "Dubai International Cricket Stadium",
            "ut": "",
            "ci": "Dubai",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5765,
        "mt": "3",
        "imt": 3,
        "mh": "Match 8",
        "md": "02/20/2019 00:00:00",
        "mti": "4:00 PM",
        "ml": "Sharjah",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "QG won by 8 wickets",
        "umr": "",
        "t1i": "62",
        "t1tt": 0,
        "t1t": "Quetta Gladiators",
        "t1n": "QG",
        "t1s": "161/2",
        "t1o": "18.3 ovs",
        "t1i1s": "161/2",
        "t1i2s": "",
        "t1i1o": "18.3 ovs",
        "t1i2o": "",
        "t2i": "104",
        "t2tt": 0,
        "t2t": "Multan Sultans",
        "t2n": "MS",
        "t2s": "160/9",
        "t2o": "20 ovs",
        "t2i1s": "160/9",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "quetta-gladiators-vs-multan-sultans-match-8-2019",
        "mVnu": {
            "id": 148,
            "oid": 156,
            "t": "Sharjah Cricket Stadium",
            "ut": "",
            "ci": "Sharjah",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5766,
        "mt": "3",
        "imt": 3,
        "mh": "Match 9",
        "md": "02/21/2019 00:00:00",
        "mti": "4:00 PM",
        "ml": "Sharjah",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "PZ won by 44 runs",
        "umr": "",
        "t1i": "61",
        "t1tt": 0,
        "t1t": "Peshawar Zalmi",
        "t1n": "PZ",
        "t1s": "153/8",
        "t1o": "20 ovs",
        "t1i1s": "153/8",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "59",
        "t2tt": 0,
        "t2t": "Karachi Kings",
        "t2n": "KK",
        "t2s": "109/9",
        "t2o": "20 ovs",
        "t2i1s": "109/9",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "peshawar-zalmi-vs-karachi-kings-match-9-2019",
        "mVnu": {
            "id": 148,
            "oid": 156,
            "t": "Sharjah Cricket Stadium",
            "ut": "",
            "ci": "Sharjah",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5767,
        "mt": "3",
        "imt": 3,
        "mh": "Match 10",
        "md": "02/22/2019 00:00:00",
        "mti": "11:30 AM",
        "ml": "Sharjah",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "LQ won by 6 wickets",
        "umr": "",
        "t1i": "104",
        "t1tt": 0,
        "t1t": "Multan Sultans",
        "t1n": "MS",
        "t1s": "200/6",
        "t1o": "20 ovs",
        "t1i1s": "200/6",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "60",
        "t2tt": 0,
        "t2t": "Lahore Qalandars",
        "t2n": "LQ",
        "t2s": "204/4",
        "t2o": "20 ovs",
        "t2i1s": "204/4",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "multan-sultans-vs-lahore-qalandars-match-10-2019",
        "mVnu": {
            "id": 148,
            "oid": 156,
            "t": "Sharjah Cricket Stadium",
            "ut": "",
            "ci": "Sharjah",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5768,
        "mt": "3",
        "imt": 3,
        "mh": "Match 11",
        "md": "02/22/2019 00:00:00",
        "mti": "4:00 PM",
        "ml": "Sharjah",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "ISLU won by 12 runs",
        "umr": "",
        "t1i": "58",
        "t1tt": 0,
        "t1t": "Islamabad United",
        "t1n": "ISLU",
        "t1s": "158/9",
        "t1o": "20 ovs",
        "t1i1s": "158/9",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "61",
        "t2tt": 0,
        "t2t": "Peshawar Zalmi",
        "t2n": "PZ",
        "t2s": "146/10",
        "t2o": "19.4 ovs",
        "t2i1s": "146/10",
        "t2i2s": "",
        "t2i1o": "19.4 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "islamabad-united-vs-peshawar-zalmi-match-11-2019",
        "mVnu": {
            "id": 148,
            "oid": 156,
            "t": "Sharjah Cricket Stadium",
            "ut": "",
            "ci": "Sharjah",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5769,
        "mt": "3",
        "imt": 3,
        "mh": "Match 12",
        "md": "02/23/2019 00:00:00",
        "mti": "11:30 AM",
        "ml": "Sharjah",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "QG won by 3 wickets",
        "umr": "",
        "t1i": "62",
        "t1tt": 0,
        "t1t": "Quetta Gladiators",
        "t1n": "QG",
        "t1s": "148/7",
        "t1o": "20 ovs",
        "t1i1s": "148/7",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "60",
        "t2tt": 0,
        "t2t": "Lahore Qalandars",
        "t2n": "LQ",
        "t2s": "143/7",
        "t2o": "20 ovs",
        "t2i1s": "143/7",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "quetta-gladiators-vs-lahore-qalandars-match-12-2019",
        "mVnu": {
            "id": 148,
            "oid": 156,
            "t": "Sharjah Cricket Stadium",
            "ut": "",
            "ci": "Sharjah",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5770,
        "mt": "3",
        "imt": 3,
        "mh": "Match 13",
        "md": "02/23/2019 00:00:00",
        "mti": "4:00 PM",
        "ml": "Sharjah",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "ISLU won by 7 wickets",
        "umr": "",
        "t1i": "58",
        "t1tt": 0,
        "t1t": "Islamabad United",
        "t1n": "ISLU",
        "t1s": "147/3",
        "t1o": "16.1 ovs",
        "t1i1s": "147/3",
        "t1i2s": "",
        "t1i1o": "16.1 ovs",
        "t1i2o": "",
        "t2i": "59",
        "t2tt": 0,
        "t2t": "Karachi Kings",
        "t2n": "KK",
        "t2s": "143/6",
        "t2o": "20 ovs",
        "t2i1s": "143/6",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "islamabad-united-vs-karachi-kings-match-13-2019",
        "mVnu": {
            "id": 148,
            "oid": 156,
            "t": "Sharjah Cricket Stadium",
            "ut": "",
            "ci": "Sharjah",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5771,
        "mt": "3",
        "imt": 3,
        "mh": "Match 14",
        "md": "02/24/2019 00:00:00",
        "mti": "11:30 AM",
        "ml": "Sharjah",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "PZ won by 5 wickets",
        "umr": "",
        "t1i": "61",
        "t1tt": 0,
        "t1t": "Peshawar Zalmi",
        "t1n": "PZ",
        "t1s": "146/5",
        "t1o": "19.4 ovs",
        "t1i1s": "146/5",
        "t1i2s": "",
        "t1i1o": "19.4 ovs",
        "t1i2o": "",
        "t2i": "104",
        "t2tt": 0,
        "t2t": "Multan Sultans",
        "t2n": "MS",
        "t2s": "145/10",
        "t2o": "20 ovs",
        "t2i1s": "145/10",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "peshawar-zalmi-vs-multan-sultans-match-14-2019",
        "mVnu": {
            "id": 148,
            "oid": 156,
            "t": "Sharjah Cricket Stadium",
            "ut": "",
            "ci": "Sharjah",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5772,
        "mt": "3",
        "imt": 3,
        "mh": "Match 15",
        "md": "02/24/2019 00:00:00",
        "mti": "4:00 PM",
        "ml": "Sharjah",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "KK won by 6 wickets",
        "umr": "",
        "t1i": "62",
        "t1tt": 0,
        "t1t": "Quetta Gladiators",
        "t1n": "QG",
        "t1s": "186/5",
        "t1o": "20 ovs",
        "t1i1s": "186/5",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "59",
        "t2tt": 0,
        "t2t": "Karachi Kings",
        "t2n": "KK",
        "t2s": "188/4",
        "t2o": "18.4 ovs",
        "t2i1s": "188/4",
        "t2i2s": "",
        "t2i1o": "18.4 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "quetta-gladiators-vs-karachi-kings-match-15-2019",
        "mVnu": {
            "id": 148,
            "oid": 156,
            "t": "Sharjah Cricket Stadium",
            "ut": "",
            "ci": "Sharjah",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5773,
        "mt": "3",
        "imt": 3,
        "mh": "Match 16",
        "md": "02/26/2019 00:00:00",
        "mti": "4:00 PM",
        "ml": "Dubai",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "MS won by 6 wickets",
        "umr": "",
        "t1i": "104",
        "t1tt": 0,
        "t1t": "Multan Sultans",
        "t1n": "MS",
        "t1s": "122/4",
        "t1o": "18.1 ovs",
        "t1i1s": "122/4",
        "t1i2s": "",
        "t1i1o": "18.1 ovs",
        "t1i2o": "",
        "t2i": "58",
        "t2tt": 0,
        "t2t": "Islamabad United",
        "t2n": "ISLU",
        "t2s": "121/10",
        "t2o": "17.4 ovs",
        "t2i1s": "121/10",
        "t2i2s": "",
        "t2i1o": "17.4 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "multan-sultans-vs-islamabad-united-match-16-2019",
        "mVnu": {
            "id": 53,
            "oid": 262,
            "t": "Dubai International Cricket Stadium",
            "ut": "",
            "ci": "Dubai",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5774,
        "mt": "3",
        "imt": 3,
        "mh": "Match 17",
        "md": "02/27/2019 00:00:00",
        "mti": "11:30 AM",
        "ml": "Dubai",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "LQ won by 8 wickets",
        "umr": "",
        "t1i": "60",
        "t1tt": 0,
        "t1t": "Lahore Qalandars",
        "t1n": "LQ",
        "t1s": "107/2",
        "t1o": "16.3 ovs",
        "t1i1s": "107/2",
        "t1i2s": "",
        "t1i1o": "16.3 ovs",
        "t1i2o": "",
        "t2i": "62",
        "t2tt": 0,
        "t2t": "Quetta Gladiators",
        "t2n": "QG",
        "t2s": "106/10",
        "t2o": "19.1 ovs",
        "t2i1s": "106/10",
        "t2i2s": "",
        "t2i1o": "19.1 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "lahore-qalandars-vs-quetta-gladiators-match-17-2019",
        "mVnu": {
            "id": 53,
            "oid": 262,
            "t": "Dubai International Cricket Stadium",
            "ut": "",
            "ci": "Dubai",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5775,
        "mt": "3",
        "imt": 3,
        "mh": "Match 18",
        "md": "02/27/2019 00:00:00",
        "mti": "4:00 PM",
        "ml": "Dubai",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "ISLU won by 5 wickets",
        "umr": "",
        "t1i": "59",
        "t1tt": 0,
        "t1t": "Karachi Kings",
        "t1n": "KK",
        "t1s": "168/8",
        "t1o": "20 ovs",
        "t1i1s": "168/8",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "58",
        "t2tt": 0,
        "t2t": "Islamabad United",
        "t2n": "ISLU",
        "t2s": "169/5",
        "t2o": "19.2 ovs",
        "t2i1s": "169/5",
        "t2i2s": "",
        "t2i1o": "19.2 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "karachi-kings-vs-islamabad-united-match-18-2019",
        "mVnu": {
            "id": 53,
            "oid": 262,
            "t": "Dubai International Cricket Stadium",
            "ut": "",
            "ci": "Dubai",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5776,
        "mt": "3",
        "imt": 3,
        "mh": "Match 19",
        "md": "02/28/2019 00:00:00",
        "mti": "11:30 AM",
        "ml": "Dubai",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "PZ won by 7 wickets",
        "umr": "",
        "t1i": "104",
        "t1tt": 0,
        "t1t": "Multan Sultans",
        "t1n": "MS",
        "t1s": "172/5",
        "t1o": "20 ovs",
        "t1i1s": "172/5",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "61",
        "t2tt": 0,
        "t2t": "Peshawar Zalmi",
        "t2n": "PZ",
        "t2s": "176/3",
        "t2o": "19.2 ovs",
        "t2i1s": "176/3",
        "t2i2s": "",
        "t2i1o": "19.2 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "multan-sultans-vs-peshawar-zalmi-match-19-2019",
        "mVnu": {
            "id": 53,
            "oid": 262,
            "t": "Dubai International Cricket Stadium",
            "ut": "",
            "ci": "Dubai",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5777,
        "mt": "3",
        "imt": 3,
        "mh": "Match 20",
        "md": "02/28/2019 00:00:00",
        "mti": "4:00 PM",
        "ml": "Dubai",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "KK won by 5 wickets",
        "umr": "",
        "t1i": "59",
        "t1tt": 0,
        "t1t": "Karachi Kings",
        "t1n": "KK",
        "t1s": "134/5",
        "t1o": "19.1 ovs",
        "t1i1s": "134/5",
        "t1i2s": "",
        "t1i1o": "19.1 ovs",
        "t1i2o": "",
        "t2i": "60",
        "t2tt": 0,
        "t2t": "Lahore Qalandars",
        "t2n": "LQ",
        "t2s": "133/5",
        "t2o": "20 ovs",
        "t2i1s": "133/5",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "karachi-kings-vs-lahore-qalandars-match-20-2019",
        "mVnu": {
            "id": 53,
            "oid": 262,
            "t": "Dubai International Cricket Stadium",
            "ut": "",
            "ci": "Dubai",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5778,
        "mt": "3",
        "imt": 3,
        "mh": "Match 21",
        "md": "03/01/2019 00:00:00",
        "mti": "11:30 AM",
        "ml": "Dubai",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "PZ won by 4 wickets",
        "umr": "",
        "t1i": "61",
        "t1tt": 0,
        "t1t": "Peshawar Zalmi",
        "t1n": "PZ",
        "t1s": "177/6",
        "t1o": "20 ovs",
        "t1i1s": "177/6",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "58",
        "t2tt": 0,
        "t2t": "Islamabad United",
        "t2n": "ISLU",
        "t2s": "176/10",
        "t2o": "20 ovs",
        "t2i1s": "176/10",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "peshawar-zalmi-vs-islamabad-united-match-21-2019",
        "mVnu": {
            "id": 53,
            "oid": 262,
            "t": "Dubai International Cricket Stadium",
            "ut": "",
            "ci": "Dubai",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5779,
        "mt": "3",
        "imt": 3,
        "mh": "Match 22",
        "md": "03/01/2019 00:00:00",
        "mti": "4:00 PM",
        "ml": "Dubai",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "QG won by 6 wickets",
        "umr": "",
        "t1i": "104",
        "t1tt": 0,
        "t1t": "Multan Sultans",
        "t1n": "MS",
        "t1s": "121/10",
        "t1o": "20 ovs",
        "t1i1s": "121/10",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "62",
        "t2tt": 0,
        "t2t": "Quetta Gladiators",
        "t2n": "QG",
        "t2s": "122/4",
        "t2o": "19 ovs",
        "t2i1s": "122/4",
        "t2i2s": "",
        "t2i1o": "19 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "multan-sultans-vs-quetta-gladiators-match-22-2019",
        "mVnu": {
            "id": 53,
            "oid": 262,
            "t": "Dubai International Cricket Stadium",
            "ut": "",
            "ci": "Dubai",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5780,
        "mt": "3",
        "imt": 3,
        "mh": "Match 23",
        "md": "03/04/2019 00:00:00",
        "mti": "11:30 AM",
        "ml": "Abu Dhabi",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "QG won by 8 wickets",
        "umr": "",
        "t1i": "62",
        "t1tt": 0,
        "t1t": "Quetta Gladiators",
        "t1n": "QG",
        "t1s": "166/2",
        "t1o": "17.4 ovs",
        "t1i1s": "166/2",
        "t1i2s": "",
        "t1i1o": "17.4 ovs",
        "t1i2o": "",
        "t2i": "61",
        "t2tt": 0,
        "t2t": "Peshawar Zalmi",
        "t2n": "PZ",
        "t2s": "165/4",
        "t2o": "20 ovs",
        "t2i1s": "165/4",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "quetta-gladiators-vs-peshawar-zalmi-match-23-2019",
        "mVnu": {
            "id": 45,
            "oid": 192,
            "t": "Sheikh Zayed Stadium",
            "ut": "",
            "ci": "Abu Dhabi",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5781,
        "mt": "3",
        "imt": 3,
        "mh": "Match 24",
        "md": "03/04/2019 00:00:00",
        "mti": "4:00 PM",
        "ml": "Abu Dhabi",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "KK won by 5 wickets",
        "umr": "",
        "t1i": "59",
        "t1tt": 0,
        "t1t": "Karachi Kings",
        "t1n": "KK",
        "t1s": "120/5",
        "t1o": "19.2 ovs",
        "t1i1s": "120/5",
        "t1i2s": "",
        "t1i1o": "19.2 ovs",
        "t1i2o": "",
        "t2i": "104",
        "t2tt": 0,
        "t2t": "Multan Sultans",
        "t2n": "MS",
        "t2s": "118/7",
        "t2o": "20 ovs",
        "t2i1s": "118/7",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "karachi-kings-vs-multan-sultans-match-24-2019",
        "mVnu": {
            "id": 45,
            "oid": 192,
            "t": "Sheikh Zayed Stadium",
            "ut": "",
            "ci": "Abu Dhabi",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5782,
        "mt": "3",
        "imt": 3,
        "mh": "Match 25",
        "md": "03/05/2019 00:00:00",
        "mti": "11:30 AM",
        "ml": "Abu Dhabi",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "PZ won by 4 wickets",
        "umr": "",
        "t1i": "60",
        "t1tt": 0,
        "t1t": "Lahore Qalandars",
        "t1n": "LQ",
        "t1s": "124/7",
        "t1o": "20 ovs",
        "t1i1s": "124/7",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "61",
        "t2tt": 0,
        "t2t": "Peshawar Zalmi",
        "t2n": "PZ",
        "t2s": "125/6",
        "t2o": "19.5 ovs",
        "t2i1s": "125/6",
        "t2i2s": "",
        "t2i1o": "19.5 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "lahore-qalandars-vs-peshawar-zalmi-match-25-2019",
        "mVnu": {
            "id": 45,
            "oid": 192,
            "t": "Sheikh Zayed Stadium",
            "ut": "",
            "ci": "Abu Dhabi",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5783,
        "mt": "3",
        "imt": 3,
        "mh": "Match 26",
        "md": "03/05/2019 00:00:00",
        "mti": "4:00 PM",
        "ml": "Abu Dhabi",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "QG won by 43 runs",
        "umr": "",
        "t1i": "62",
        "t1tt": 0,
        "t1t": "Quetta Gladiators",
        "t1n": "QG",
        "t1s": "180/9",
        "t1o": "20 ovs",
        "t1i1s": "180/9",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "58",
        "t2tt": 0,
        "t2t": "Islamabad United",
        "t2n": "ISLU",
        "t2s": "137/9",
        "t2o": "20 ovs",
        "t2i1s": "137/9",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "quetta-gladiators-vs-islamabad-united-match-26-2019",
        "mVnu": {
            "id": 45,
            "oid": 192,
            "t": "Sheikh Zayed Stadium",
            "ut": "",
            "ci": "Abu Dhabi",
            "co": "United Arab Emirates"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5784,
        "mt": "3",
        "imt": 3,
        "mh": "Match 27",
        "md": "03/09/2019 00:00:00",
        "mti": "2:00 PM",
        "ml": "Karachi",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "ISLU won by 49 runs",
        "umr": "",
        "t1i": "60",
        "t1tt": 0,
        "t1t": "Lahore Qalandars",
        "t1n": "LQ",
        "t1s": "189/9",
        "t1o": "20 ovs",
        "t1i1s": "189/9",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "58",
        "t2tt": 0,
        "t2t": "Islamabad United",
        "t2n": "ISLU",
        "t2s": "238/3",
        "t2o": "20 ovs",
        "t2i1s": "238/3",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "lahore-qalandars-vs-islamabad-united-match-27-2019",
        "mVnu": {
            "id": 149,
            "oid": 44,
            "t": "National Stadium",
            "ut": "",
            "ci": "Karachi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5785,
        "mt": "3",
        "imt": 3,
        "mh": "Match 28",
        "md": "03/10/2019 00:00:00",
        "mti": "2:00 PM",
        "ml": "Karachi",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "KK won by 1 runs",
        "umr": "",
        "t1i": "59",
        "t1tt": 0,
        "t1t": "Karachi Kings",
        "t1n": "KK",
        "t1s": "190/5",
        "t1o": "20 ovs",
        "t1i1s": "190/5",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "62",
        "t2tt": 0,
        "t2t": "Quetta Gladiators",
        "t2n": "QG",
        "t2s": "189/7",
        "t2o": "20 ovs",
        "t2i1s": "189/7",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "karachi-kings-vs-quetta-gladiators-match-28-2019",
        "mVnu": {
            "id": 143,
            "oid": 0,
            "t": "National Stadium Karachi",
            "ut": "",
            "ci": "Karachi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5786,
        "mt": "3",
        "imt": 3,
        "mh": "Match 29",
        "md": "03/11/2019 00:00:00",
        "mti": "9:00 AM",
        "ml": "Karachi",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "MS won by 7 wickets",
        "umr": "",
        "t1i": "60",
        "t1tt": 0,
        "t1t": "Lahore Qalandars",
        "t1n": "LQ",
        "t1s": "140/8",
        "t1o": "20 ovs",
        "t1i1s": "140/8",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "104",
        "t2tt": 0,
        "t2t": "Multan Sultans",
        "t2n": "MS",
        "t2s": "141/3",
        "t2o": "12.3 ovs",
        "t2i1s": "141/3",
        "t2i2s": "",
        "t2i1o": "12.3 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "lahore-qalandars-vs-multan-sultans-match-29-2019",
        "mVnu": {
            "id": 149,
            "oid": 44,
            "t": "National Stadium",
            "ut": "",
            "ci": "Karachi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5787,
        "mt": "3",
        "imt": 3,
        "mh": "Match 30",
        "md": "03/11/2019 00:00:00",
        "mti": "2:00 PM",
        "ml": "Karachi",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "PZ won by 61 runs",
        "umr": "",
        "t1i": "59",
        "t1tt": 0,
        "t1t": "Karachi Kings",
        "t1n": "KK",
        "t1s": "142/10",
        "t1o": "16.2 ovs",
        "t1i1s": "142/10",
        "t1i2s": "",
        "t1i1o": "16.2 ovs",
        "t1i2o": "",
        "t2i": "61",
        "t2tt": 0,
        "t2t": "Peshawar Zalmi",
        "t2n": "PZ",
        "t2s": "203/7",
        "t2o": "20 ovs",
        "t2i1s": "203/7",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "karachi-kings-vs-peshawar-zalmi-match-30-2019",
        "mVnu": {
            "id": 143,
            "oid": 0,
            "t": "National Stadium Karachi",
            "ut": "",
            "ci": "Karachi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5788,
        "mt": "3",
        "imt": 3,
        "mh": "Qualifier",
        "md": "03/13/2019 00:00:00",
        "mti": "2:00 PM",
        "ml": "Karachi",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "QG won by 10 runs",
        "umr": "",
        "t1i": "62",
        "t1tt": 0,
        "t1t": "Quetta Gladiators",
        "t1n": "QG",
        "t1s": "186/6",
        "t1o": "20 ovs",
        "t1i1s": "186/6",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "61",
        "t2tt": 0,
        "t2t": "Peshawar Zalmi",
        "t2n": "PZ",
        "t2s": "176/7",
        "t2o": "20 ovs",
        "t2i1s": "176/7",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "quetta-gladiators-vs-peshawar-zalmi-qualifier-2019",
        "mVnu": {
            "id": 143,
            "oid": 0,
            "t": "National Stadium Karachi",
            "ut": "",
            "ci": "Karachi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5789,
        "mt": "3",
        "imt": 3,
        "mh": "Eliminator 1",
        "md": "03/14/2019 00:00:00",
        "mti": "2:00 PM",
        "ml": "Karachi",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "ISLU won by 4 wickets",
        "umr": "",
        "t1i": "58",
        "t1tt": 0,
        "t1t": "Islamabad United",
        "t1n": "ISLU",
        "t1s": "164/6",
        "t1o": "19.3 ovs",
        "t1i1s": "164/6",
        "t1i2s": "",
        "t1i1o": "19.3 ovs",
        "t1i2o": "",
        "t2i": "59",
        "t2tt": 0,
        "t2t": "Karachi Kings",
        "t2n": "KK",
        "t2s": "161/9",
        "t2o": "20 ovs",
        "t2i1s": "161/9",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "islamabad-united-vs-karachi-kings-eliminator-1-2019",
        "mVnu": {
            "id": 149,
            "oid": 44,
            "t": "National Stadium",
            "ut": "",
            "ci": "Karachi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5790,
        "mt": "3",
        "imt": 3,
        "mh": "Eliminator 2",
        "md": "03/15/2019 00:00:00",
        "mti": "2:00 PM",
        "ml": "Karachi",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "PZ won by 48 runs",
        "umr": "",
        "t1i": "58",
        "t1tt": 0,
        "t1t": "Islamabad United",
        "t1n": "ISLU",
        "t1s": "166/9",
        "t1o": "20 ovs",
        "t1i1s": "166/9",
        "t1i2s": "",
        "t1i1o": "20 ovs",
        "t1i2o": "",
        "t2i": "61",
        "t2tt": 0,
        "t2t": "Peshawar Zalmi",
        "t2n": "PZ",
        "t2s": "214/5",
        "t2o": "20 ovs",
        "t2i1s": "214/5",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "islamabad-united-vs-peshawar-zalmi-eliminator-2-2019",
        "mVnu": {
            "id": 149,
            "oid": 44,
            "t": "National Stadium",
            "ut": "",
            "ci": "Karachi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 5791,
        "mt": "3",
        "imt": 3,
        "mh": "Final",
        "md": "03/17/2019 00:00:00",
        "mti": "3:00 PM",
        "ml": "Karachi",
        "ms": 0,
        "mst": 0,
        "cs": "",
        "mr": "QG won by 8 wickets",
        "umr": "",
        "t1i": "62",
        "t1tt": 0,
        "t1t": "Quetta Gladiators",
        "t1n": "QG",
        "t1s": "139/2",
        "t1o": "17.5 ovs",
        "t1i1s": "139/2",
        "t1i2s": "",
        "t1i1o": "17.5 ovs",
        "t1i2o": "",
        "t2i": "61",
        "t2tt": 0,
        "t2t": "Peshawar Zalmi",
        "t2n": "PZ",
        "t2s": "138/8",
        "t2o": "20 ovs",
        "t2i1s": "138/8",
        "t2i2s": "",
        "t2i1o": "20 ovs",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "quetta-gladiators-vs-peshawar-zalmi-final-2019",
        "mVnu": {
            "id": 149,
            "oid": 44,
            "t": "National Stadium",
            "ut": "",
            "ci": "Karachi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    }
]