export const schedule = [
    {
        "mid": 6825,
        "mt": "3",
        "imt": 3,
        "mh": "1st Match",
        "md": "02/20/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Karachi",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "62",
        "t1tt": 0,
        "t1t": "Quetta Gladiators",
        "t1n": "QG",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "58",
        "t2tt": 0,
        "t2t": "Islamabad United",
        "t2n": "ISLU",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "quetta-gladiators-vs-islamabad-united-1st-match-2020",
        "mVnu": {
            "id": 143,
            "oid": 0,
            "t": "National Stadium Karachi",
            "ut": "",
            "ci": "Karachi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7386,
        "mt": "3",
        "imt": 3,
        "mh": "2nd Match",
        "md": "02/21/2020 00:00:00",
        "mti": "9:00 AM",
        "ml": "Karachi",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "59",
        "t1tt": 0,
        "t1t": "Karachi Kings",
        "t1n": "KK",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "61",
        "t2tt": 0,
        "t2t": "Peshawar Zalmi",
        "t2n": "PZ",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "karachi-kings-vs-peshawar-zalmi-2nd-match-2020",
        "mVnu": {
            "id": 143,
            "oid": 0,
            "t": "National Stadium Karachi",
            "ut": "",
            "ci": "Karachi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7387,
        "mt": "3",
        "imt": 3,
        "mh": "3rd Match",
        "md": "02/21/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Lahore",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "60",
        "t1tt": 0,
        "t1t": "Lahore Qalandars",
        "t1n": "LQ",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "104",
        "t2tt": 0,
        "t2t": "Multan Sultans",
        "t2n": "MS",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "lahore-qalandars-vs-multan-sultans-3rd-match-2020",
        "mVnu": {
            "id": 150,
            "oid": 35,
            "t": "Gaddafi Stadium",
            "ut": "",
            "ci": "Lahore",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7388,
        "mt": "3",
        "imt": 3,
        "mh": "4th Match",
        "md": "02/22/2020 00:00:00",
        "mti": "9:00 AM",
        "ml": "Karachi",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "62",
        "t1tt": 0,
        "t1t": "Quetta Gladiators",
        "t1n": "QG",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "61",
        "t2tt": 0,
        "t2t": "Peshawar Zalmi",
        "t2n": "PZ",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "quetta-gladiators-vs-peshawar-zalmi-4th-match-2020",
        "mVnu": {
            "id": 143,
            "oid": 0,
            "t": "National Stadium Karachi",
            "ut": "",
            "ci": "Karachi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7389,
        "mt": "3",
        "imt": 3,
        "mh": "5th Match",
        "md": "02/22/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Lahore",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "58",
        "t1tt": 0,
        "t1t": "Islamabad United",
        "t1n": "ISLU",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "104",
        "t2tt": 0,
        "t2t": "Multan Sultans",
        "t2n": "MS",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "islamabad-united-vs-multan-sultans-5th-match-2020",
        "mVnu": {
            "id": 150,
            "oid": 35,
            "t": "Gaddafi Stadium",
            "ut": "",
            "ci": "Lahore",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7390,
        "mt": "3",
        "imt": 3,
        "mh": "6th Match",
        "md": "02/23/2020 00:00:00",
        "mti": "9:00 AM",
        "ml": "Karachi",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "59",
        "t1tt": 0,
        "t1t": "Karachi Kings",
        "t1n": "KK",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "62",
        "t2tt": 0,
        "t2t": "Quetta Gladiators",
        "t2n": "QG",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "karachi-kings-vs-quetta-gladiators-6th-match-2020",
        "mVnu": {
            "id": 143,
            "oid": 0,
            "t": "National Stadium Karachi",
            "ut": "",
            "ci": "Karachi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7391,
        "mt": "3",
        "imt": 3,
        "mh": "7th Match",
        "md": "02/23/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Karachi",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "60",
        "t1tt": 0,
        "t1t": "Lahore Qalandars",
        "t1n": "LQ",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "58",
        "t2tt": 0,
        "t2t": "Islamabad United",
        "t2n": "ISLU",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "lahore-qalandars-vs-islamabad-united-7th-match-2020",
        "mVnu": {
            "id": 143,
            "oid": 0,
            "t": "National Stadium Karachi",
            "ut": "",
            "ci": "Karachi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7392,
        "mt": "3",
        "imt": 3,
        "mh": "8th Match",
        "md": "02/26/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Multan",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "104",
        "t1tt": 0,
        "t1t": "Multan Sultans",
        "t1n": "MS",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "61",
        "t2tt": 0,
        "t2t": "Peshawar Zalmi",
        "t2n": "PZ",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "multan-sultans-vs-peshawar-zalmi-8th-match-2020",
        "mVnu": {
            "id": 286,
            "oid": 175,
            "t": "Multan Cricket Stadium",
            "ut": "",
            "ci": "Multan",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7393,
        "mt": "3",
        "imt": 3,
        "mh": "9th Match",
        "md": "02/27/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Multan",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "58",
        "t1tt": 0,
        "t1t": "Islamabad United",
        "t1n": "ISLU",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "62",
        "t2tt": 0,
        "t2t": "Quetta Gladiators",
        "t2n": "QG",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "islamabad-united-vs-quetta-gladiators-9th-match-2020",
        "mVnu": {
            "id": 286,
            "oid": 175,
            "t": "Multan Cricket Stadium",
            "ut": "",
            "ci": "Multan",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7394,
        "mt": "3",
        "imt": 3,
        "mh": "10th Match",
        "md": "02/28/2020 00:00:00",
        "mti": "9:00 AM",
        "ml": "Multan",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "104",
        "t1tt": 0,
        "t1t": "Multan Sultans",
        "t1n": "MS",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "59",
        "t2tt": 0,
        "t2t": "Karachi Kings",
        "t2n": "KK",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "multan-sultans-vs-karachi-kings-10th-match-2020",
        "mVnu": {
            "id": 286,
            "oid": 175,
            "t": "Multan Cricket Stadium",
            "ut": "",
            "ci": "Multan",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7395,
        "mt": "3",
        "imt": 3,
        "mh": "11th Match",
        "md": "02/28/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Rawalpindi",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "61",
        "t1tt": 0,
        "t1t": "Peshawar Zalmi",
        "t1n": "PZ",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "60",
        "t2tt": 0,
        "t2t": "Lahore Qalandars",
        "t2n": "LQ",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "peshawar-zalmi-vs-lahore-qalandars-11th-match-2020",
        "mVnu": {
            "id": 196,
            "oid": 72,
            "t": "Rawalpindi Cricket Stadium",
            "ut": "",
            "ci": "Rawalpindi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7396,
        "mt": "3",
        "imt": 3,
        "mh": "12th Match",
        "md": "02/29/2020 00:00:00",
        "mti": "9:00 AM",
        "ml": "Multan",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "104",
        "t1tt": 0,
        "t1t": "Multan Sultans",
        "t1n": "MS",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "62",
        "t2tt": 0,
        "t2t": "Quetta Gladiators",
        "t2n": "QG",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "multan-sultans-vs-quetta-gladiators-12th-match-2020",
        "mVnu": {
            "id": 286,
            "oid": 175,
            "t": "Multan Cricket Stadium",
            "ut": "",
            "ci": "Multan",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7397,
        "mt": "3",
        "imt": 3,
        "mh": "13th Match",
        "md": "02/29/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Rawalpindi",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "58",
        "t1tt": 0,
        "t1t": "Islamabad United",
        "t1n": "ISLU",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "61",
        "t2tt": 0,
        "t2t": "Peshawar Zalmi",
        "t2n": "PZ",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "islamabad-united-vs-peshawar-zalmi-13th-match-2020",
        "mVnu": {
            "id": 196,
            "oid": 72,
            "t": "Rawalpindi Cricket Stadium",
            "ut": "",
            "ci": "Rawalpindi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7398,
        "mt": "3",
        "imt": 3,
        "mh": "14th Match",
        "md": "03/01/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Rawalpindi",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "58",
        "t1tt": 0,
        "t1t": "Islamabad United",
        "t1n": "ISLU",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "59",
        "t2tt": 0,
        "t2t": "Karachi Kings",
        "t2n": "KK",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "islamabad-united-vs-karachi-kings-14th-match-2020",
        "mVnu": {
            "id": 196,
            "oid": 72,
            "t": "Rawalpindi Cricket Stadium",
            "ut": "",
            "ci": "Rawalpindi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7399,
        "mt": "3",
        "imt": 3,
        "mh": "15th Match",
        "md": "03/02/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Rawalpindi",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "61",
        "t1tt": 0,
        "t1t": "Peshawar Zalmi",
        "t1n": "PZ",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "59",
        "t2tt": 0,
        "t2t": "Karachi Kings",
        "t2n": "KK",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "peshawar-zalmi-vs-karachi-kings-15th-match-2020",
        "mVnu": {
            "id": 196,
            "oid": 72,
            "t": "Rawalpindi Cricket Stadium",
            "ut": "",
            "ci": "Rawalpindi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7400,
        "mt": "3",
        "imt": 3,
        "mh": "16th Match",
        "md": "03/03/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Lahore",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "62",
        "t1tt": 0,
        "t1t": "Quetta Gladiators",
        "t1n": "QG",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "60",
        "t2tt": 0,
        "t2t": "Lahore Qalandars",
        "t2n": "LQ",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "quetta-gladiators-vs-lahore-qalandars-16th-match-2020",
        "mVnu": {
            "id": 150,
            "oid": 35,
            "t": "Gaddafi Stadium",
            "ut": "",
            "ci": "Lahore",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7401,
        "mt": "3",
        "imt": 3,
        "mh": "17th Match",
        "md": "03/04/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Lahore",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "58",
        "t1tt": 0,
        "t1t": "Islamabad United",
        "t1n": "ISLU",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "60",
        "t2tt": 0,
        "t2t": "Lahore Qalandars",
        "t2n": "LQ",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "islamabad-united-vs-lahore-qalandars-17th-match-2020",
        "mVnu": {
            "id": 150,
            "oid": 35,
            "t": "Gaddafi Stadium",
            "ut": "",
            "ci": "Lahore",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7402,
        "mt": "3",
        "imt": 3,
        "mh": "18th Match",
        "md": "03/05/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Rawalpindi",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "61",
        "t1tt": 0,
        "t1t": "Peshawar Zalmi",
        "t1n": "PZ",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "62",
        "t2tt": 0,
        "t2t": "Quetta Gladiators",
        "t2n": "QG",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "peshawar-zalmi-vs-quetta-gladiators-18th-match-2020",
        "mVnu": {
            "id": 196,
            "oid": 72,
            "t": "Rawalpindi Cricket Stadium",
            "ut": "",
            "ci": "Rawalpindi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7403,
        "mt": "3",
        "imt": 3,
        "mh": "19th Match",
        "md": "03/06/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Lahore",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "59",
        "t1tt": 0,
        "t1t": "Karachi Kings",
        "t1n": "KK",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "104",
        "t2tt": 0,
        "t2t": "Multan Sultans",
        "t2n": "MS",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "karachi-kings-vs-multan-sultans-19th-match-2020",
        "mVnu": {
            "id": 150,
            "oid": 35,
            "t": "Gaddafi Stadium",
            "ut": "",
            "ci": "Lahore",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7404,
        "mt": "3",
        "imt": 3,
        "mh": "20th Match",
        "md": "03/07/2020 00:00:00",
        "mti": "9:00 AM",
        "ml": "Rawalpindi",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "61",
        "t1tt": 0,
        "t1t": "Peshawar Zalmi",
        "t1n": "PZ",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "58",
        "t2tt": 0,
        "t2t": "Islamabad United",
        "t2n": "ISLU",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "peshawar-zalmi-vs-islamabad-united-20th-match-2020",
        "mVnu": {
            "id": 196,
            "oid": 72,
            "t": "Rawalpindi Cricket Stadium",
            "ut": "",
            "ci": "Rawalpindi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7405,
        "mt": "3",
        "imt": 3,
        "mh": "21st Match",
        "md": "03/07/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Lahore",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "60",
        "t1tt": 0,
        "t1t": "Lahore Qalandars",
        "t1n": "LQ",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "62",
        "t2tt": 0,
        "t2t": "Quetta Gladiators",
        "t2n": "QG",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "lahore-qalandars-vs-quetta-gladiators-21st-match-2020",
        "mVnu": {
            "id": 150,
            "oid": 35,
            "t": "Gaddafi Stadium",
            "ut": "",
            "ci": "Lahore",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7406,
        "mt": "3",
        "imt": 3,
        "mh": "22nd Match",
        "md": "03/08/2020 00:00:00",
        "mti": "9:00 AM",
        "ml": "Rawalpindi",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "104",
        "t1tt": 0,
        "t1t": "Multan Sultans",
        "t1n": "MS",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "58",
        "t2tt": 0,
        "t2t": "Islamabad United",
        "t2n": "ISLU",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "multan-sultans-vs-islamabad-united-22nd-match-2020",
        "mVnu": {
            "id": 196,
            "oid": 72,
            "t": "Rawalpindi Cricket Stadium",
            "ut": "",
            "ci": "Rawalpindi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7407,
        "mt": "3",
        "imt": 3,
        "mh": "23rd Match",
        "md": "03/08/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Lahore",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "60",
        "t1tt": 0,
        "t1t": "Lahore Qalandars",
        "t1n": "LQ",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "59",
        "t2tt": 0,
        "t2t": "Karachi Kings",
        "t2n": "KK",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "lahore-qalandars-vs-karachi-kings-23rd-match-2020",
        "mVnu": {
            "id": 150,
            "oid": 35,
            "t": "Gaddafi Stadium",
            "ut": "",
            "ci": "Lahore",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7408,
        "mt": "3",
        "imt": 3,
        "mh": "24th Match",
        "md": "03/10/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Lahore",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "60",
        "t1tt": 0,
        "t1t": "Lahore Qalandars",
        "t1n": "LQ",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "61",
        "t2tt": 0,
        "t2t": "Peshawar Zalmi",
        "t2n": "PZ",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "lahore-qalandars-vs-peshawar-zalmi-24th-match-2020",
        "mVnu": {
            "id": 150,
            "oid": 35,
            "t": "Gaddafi Stadium",
            "ut": "",
            "ci": "Lahore",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7409,
        "mt": "3",
        "imt": 3,
        "mh": "25th Match",
        "md": "03/11/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Lahore",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "62",
        "t1tt": 0,
        "t1t": "Quetta Gladiators",
        "t1n": "QG",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "104",
        "t2tt": 0,
        "t2t": "Multan Sultans",
        "t2n": "MS",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "quetta-gladiators-vs-multan-sultans-25th-match-2020",
        "mVnu": {
            "id": 150,
            "oid": 35,
            "t": "Gaddafi Stadium",
            "ut": "",
            "ci": "Lahore",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7410,
        "mt": "3",
        "imt": 3,
        "mh": "26th Match",
        "md": "03/12/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Karachi",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "59",
        "t1tt": 0,
        "t1t": "Karachi Kings",
        "t1n": "KK",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "60",
        "t2tt": 0,
        "t2t": "Lahore Qalandars",
        "t2n": "LQ",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "karachi-kings-vs-lahore-qalandars-26th-match-2020",
        "mVnu": {
            "id": 143,
            "oid": 0,
            "t": "National Stadium Karachi",
            "ut": "",
            "ci": "Karachi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7411,
        "mt": "3",
        "imt": 3,
        "mh": "27th Match",
        "md": "03/13/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Karachi",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "61",
        "t1tt": 0,
        "t1t": "Peshawar Zalmi",
        "t1n": "PZ",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "104",
        "t2tt": 0,
        "t2t": "Multan Sultans",
        "t2n": "MS",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "peshawar-zalmi-vs-multan-sultans-27th-match-2020",
        "mVnu": {
            "id": 143,
            "oid": 0,
            "t": "National Stadium Karachi",
            "ut": "",
            "ci": "Karachi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7412,
        "mt": "3",
        "imt": 3,
        "mh": "28th Match",
        "md": "03/14/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Karachi",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "59",
        "t1tt": 0,
        "t1t": "Karachi Kings",
        "t1n": "KK",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "58",
        "t2tt": 0,
        "t2t": "Islamabad United",
        "t2n": "ISLU",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "karachi-kings-vs-islamabad-united-28th-match-2020",
        "mVnu": {
            "id": 143,
            "oid": 0,
            "t": "National Stadium Karachi",
            "ut": "",
            "ci": "Karachi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7413,
        "mt": "3",
        "imt": 3,
        "mh": "29th Match",
        "md": "03/15/2020 00:00:00",
        "mti": "9:00 AM",
        "ml": "Lahore",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "104",
        "t1tt": 0,
        "t1t": "Multan Sultans",
        "t1n": "MS",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "60",
        "t2tt": 0,
        "t2t": "Lahore Qalandars",
        "t2n": "LQ",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "multan-sultans-vs-lahore-qalandars-29th-match-2020",
        "mVnu": {
            "id": 150,
            "oid": 35,
            "t": "Gaddafi Stadium",
            "ut": "",
            "ci": "Lahore",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7414,
        "mt": "3",
        "imt": 3,
        "mh": "30th Match",
        "md": "03/15/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Karachi",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "62",
        "t1tt": 0,
        "t1t": "Quetta Gladiators",
        "t1n": "QG",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "59",
        "t2tt": 0,
        "t2t": "Karachi Kings",
        "t2n": "KK",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "quetta-gladiators-vs-karachi-kings-30th-match-2020",
        "mVnu": {
            "id": 143,
            "oid": 0,
            "t": "National Stadium Karachi",
            "ut": "",
            "ci": "Karachi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": true,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7415,
        "mt": "3",
        "imt": 3,
        "mh": "Qualifier",
        "md": "03/17/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Karachi",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "29",
        "t1tt": 0,
        "t1t": "TBD",
        "t1n": "TBD",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "30",
        "t2tt": 0,
        "t2t": "TBD",
        "t2n": "TBD",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "qualifier-2020",
        "mVnu": {
            "id": 143,
            "oid": 0,
            "t": "National Stadium Karachi",
            "ut": "",
            "ci": "Karachi",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": false,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7416,
        "mt": "3",
        "imt": 3,
        "mh": "Eliminator 1",
        "md": "03/18/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Lahore",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "29",
        "t1tt": 0,
        "t1t": "TBD",
        "t1n": "TBD",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "30",
        "t2tt": 0,
        "t2t": "TBD",
        "t2n": "TBD",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "eliminator-1-2020",
        "mVnu": {
            "id": 150,
            "oid": 35,
            "t": "Gaddafi Stadium",
            "ut": "",
            "ci": "Lahore",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": false,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7417,
        "mt": "3",
        "imt": 3,
        "mh": "Eliminator 2",
        "md": "03/20/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Lahore",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "29",
        "t1tt": 0,
        "t1t": "TBD",
        "t1n": "TBD",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "30",
        "t2tt": 0,
        "t2t": "TBD",
        "t2n": "TBD",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "eliminator-2-2020",
        "mVnu": {
            "id": 150,
            "oid": 35,
            "t": "Gaddafi Stadium",
            "ut": "",
            "ci": "Lahore",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": false,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    },
    {
        "mid": 7418,
        "mt": "3",
        "imt": 3,
        "mh": "FINAL",
        "md": "03/22/2020 00:00:00",
        "mti": "2:00 PM",
        "ml": "Lahore",
        "ms": 2,
        "mst": 0,
        "cs": "",
        "mr": "",
        "umr": "",
        "t1i": "29",
        "t1tt": 0,
        "t1t": "TBD",
        "t1n": "TBD",
        "t1s": "",
        "t1o": "",
        "t1i1s": "",
        "t1i2s": "",
        "t1i1o": "",
        "t1i2o": "",
        "t2i": "30",
        "t2tt": 0,
        "t2t": "TBD",
        "t2n": "TBD",
        "t2s": "",
        "t2o": "",
        "t2i1s": "",
        "t2i2s": "",
        "t2i1o": "",
        "t2i2o": "",
        "cov": null,
        "bt": 0,
        "st": "",
        "str": null,
        "sId": null,
        "strhn": null,
        "strh": null,
        "tId": "",
        "mslug": "",
        "t1ut": "",
        "uh": "",
        "uv": "",
        "vt": "",
        "t2ut": "",
        "ipl": 0,
        "slug": "final-2020",
        "mVnu": {
            "id": 150,
            "oid": 35,
            "t": "Gaddafi Stadium",
            "ut": "",
            "ci": "Lahore",
            "co": "Pakistan"
        },
        "cp": null,
        "fow": null,
        "btid": 0,
        "qe": false,
        "ee": false,
        "ft": 0,
        "spt": false,
        "pst": 0,
        "up": ""
    }
]