export const player = [
    {
        "Id": 19300,
        "fn": "Akif Javed",
        "n": "Akif Javed",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 0
    },
    {
        "Id": 11992,
        "fn": "Dale Willem Steyn",
        "n": "Dale Steyn",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 508
    },
    {
        "Id": 17368,
        "fn": "Hendrik Erasmus van der Dussen",
        "n": "Rassie van der Dussen",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 9554
    },
    {
        "Id": 15408,
        "fn": "Saif Badar",
        "n": "Saif Badar",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 11192
    },
    {
        "Id": 23725,
        "fn": "Ahmed Safi Abdullah",
        "n": "Ahmed Safi Abdullah",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 0
    },
    {
        "Id": 13026,
        "fn": "Arshad Khan",
        "n": "Arshad Khan",
        "nn": "",
        "bts": true,
        "bs": "Right-arm offbreak",
        "d": "",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 369
    },
    {
        "Id": 20521,
        "fn": "Dan Lawrence",
        "n": "Dan Lawrence",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 10385
    },
    {
        "Id": 11211,
        "fn": "Liam Edward Plunkett",
        "n": "Liam Plunkett",
        "nn": "",
        "bts": false,
        "bs": "Bowler",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 479
    },
    {
        "Id": 13727,
        "fn": "Sharjeel Khan",
        "n": "Sharjeel Khan",
        "nn": "",
        "bts": false,
        "bs": "Left-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 9052
    },
    {
        "Id": 15779,
        "fn": "Muhammad Ashan Ali Khan",
        "n": "Ali Khan",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 11450
    },
    {
        "Id": 14142,
        "fn": "Christopher Austin Lynn",
        "n": "Chris Lynn",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 7752
    },
    {
        "Id": 20527,
        "fn": "Dilbar Hussain",
        "n": "Dilbar Hussain",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 15708
    },
    {
        "Id": 13217,
        "fn": "Seekkuge Prasanna",
        "n": "Seekkuge Prasanna",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 0
    },
    {
        "Id": 23726,
        "fn": "Mohammad Faizan",
        "n": "Mohammad Faizan",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 0
    },
    {
        "Id": 23727,
        "fn": "Farzan Raja",
        "n": "Farzan Raja",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 0
    },
    {
        "Id": 12005,
        "fn": "Mohammad Imran Tahir",
        "n": "Imran Tahir",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 6667
    },
    {
        "Id": 11245,
        "fn": "Moeen Munir Ali",
        "n": "Moeen Ali",
        "nn": "",
        "bts": false,
        "bs": "Batting allrounder",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 6692
    },
    {
        "Id": 18893,
        "fn": "Zeeshan Ashraf",
        "n": "Zeeshan Ashraf",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 0
    },
    {
        "Id": 15403,
        "fn": "Khushdil Shah",
        "n": "Khushdil Shah",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 12565
    },
    {
        "Id": 15402,
        "fn": "Usman Qadir",
        "n": "Usman Qadir",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8373
    },
    {
        "Id": 15795,
        "fn": "Fabian Allen",
        "n": "Fabian Allen",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 9785
    },
    {
        "Id": 15902,
        "fn": "Rohail Nazir",
        "n": "Rohail Nazir",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 13192
    },
    {
        "Id": 13094,
        "fn": "Bilawal Bhatti",
        "n": "Bilawal Bhatti",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8582
    },
    {
        "Id": 16009,
        "fn": "Tom Banton",
        "n": "Tom Banton",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 12254
    },
    {
        "Id": 19022,
        "fn": "Mohammad Mohsin",
        "n": "Mohammad Mohsin",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 0
    },
    {
        "Id": 13543,
        "fn": "Dwaine Pretorius",
        "n": "Dwaine Pretorius",
        "nn": "",
        "bts": true,
        "bs": "Right-arm medium-fast",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8651
    },
    {
        "Id": 22675,
        "fn": "Aamir Khan",
        "n": "Aamir Khan",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 15850
    },
    {
        "Id": 22687,
        "fn": "Aamir Ali",
        "n": "Aamir Ali",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 15135
    },
    {
        "Id": 19013,
        "fn": "Haider Ali",
        "n": "Haider Ali",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 15037
    },
    {
        "Id": 15512,
        "fn": "Adil Amin",
        "n": "Adil Amin",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 14373
    },
    {
        "Id": 19010,
        "fn": "Aarish Ali Khan",
        "n": "Aarish Ali Khan",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 0
    },
    {
        "Id": 13015,
        "fn": "Mohammad Azam Khan",
        "n": "Azam Khan",
        "nn": "",
        "bts": true,
        "bs": "",
        "d": "",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 3747
    },
    {
        "Id": 13493,
        "fn": "Benjamin Colin James Cutting",
        "n": "Ben Cutting",
        "nn": "",
        "bts": false,
        "bs": "Allrounder",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8118
    },
    {
        "Id": 13460,
        "fn": "Jason Jonathan Roy",
        "n": "Jason Roy",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 6534
    },
    {
        "Id": 15809,
        "fn": "Keemo Paul",
        "n": "Keemo Paul",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 11214
    },
    {
        "Id": 13067,
        "fn": "Khurram Manzoor",
        "n": "Khurram Manzoor",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 1044
    },
    {
        "Id": 23724,
        "fn": "Abdul Nasir",
        "n": "Abdul Nasir",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 0
    }
]