

export const PZ = [
    {
        "Id": 13046,
        "fn": "Shoaib Malik",
        "n": "Shoaib Malik",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 33
    },
    {
        "Id": 13088,
        "fn": "Rahat Ali",
        "n": "Rahat Ali",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8301
    },
    {
        "Id": 13079,
        "fn": "Wahab Riaz",
        "n": "Wahab Riaz",
        "nn": "",
        "bts": false,
        "bs": "Bowler",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 1051
    },
    {
        "Id": 12285,
        "fn": "Darren Julius Garvey Sammy",
        "n": "Daren Sammy",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 253
    },
    {
        "Id": 13735,
        "fn": "Hasan Ali",
        "n": "Hasan Ali",
        "nn": "",
        "bts": true,
        "bs": "Right-arm medium-fast",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 11320
    },
    {
        "Id": 13049,
        "fn": "Kamran Akmal",
        "n": "Kamran Akmal",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 77
    },
    {
        "Id": 13464,
        "fn": "Liam Andrew Dawson",
        "n": "Liam Dawson",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 6639
    },
    {
        "Id": 13558,
        "fn": "Kieron Adrian Pollard",
        "n": "Kieron Pollard",
        "nn": "",
        "bts": false,
        "bs": "Right-hand bat",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 657
    },
    {
        "Id": 13077,
        "fn": "Umar Amin",
        "n": "Umar Amin",
        "nn": "",
        "bts": false,
        "bs": "Left-hand bat",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 1740
    },
    {
        "Id": 15819,
        "fn": "Imam-ul-Haq",
        "n": "Imam-ul-Haq",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8364
    },
    {
        "Id": 16009,
        "fn": "Tom Banton",
        "n": "Tom Banton",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 12254
    },
    {
        "Id": 19022,
        "fn": "Mohammad Mohsin",
        "n": "Mohammad Mohsin",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 0
    },
    {
        "Id": 13543,
        "fn": "Dwaine Pretorius",
        "n": "Dwaine Pretorius",
        "nn": "",
        "bts": true,
        "bs": "Right-arm medium-fast",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 8651
    },
    {
        "Id": 22675,
        "fn": "Aamir Khan",
        "n": "Aamir Khan",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 15850
    },
    {
        "Id": 22687,
        "fn": "Aamir Ali",
        "n": "Aamir Ali",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 15135
    },
    {
        "Id": 15487,
        "fn": "Liam Livingstone",
        "n": "Liam Livingstone",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Batsman",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 10045
    },
    {
        "Id": 19013,
        "fn": "Haider Ali",
        "n": "Haider Ali",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "Bowler",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 15037
    },
    {
        "Id": 15512,
        "fn": "Adil Amin",
        "n": "Adil Amin",
        "nn": "",
        "bts": false,
        "bs": "",
        "d": "All Rounder",
        "un": "",
        "ine": false,
        "tids": null,
        "cbId": 14373
    }
];
export const LQ = [{ "Id": 14145, "fn": "Ben Robert Dunk", "n": "Ben Dunk", "nn": "", "bts": false, "bs": "Left-hand bat", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 8142 }, { "Id": 14142, "fn": "Christopher Austin Lynn", "n": "Chris Lynn", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 7752 }, { "Id": 13540, "fn": "David Wiese", "n": "David Wiese", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 8589 }, { "Id": 20527, "fn": "Dilbar Hussain", "n": "Dilbar Hussain", "nn": "", "bts": false, "bs": "", "d": "", "un": "", "ine": false, "tids": null, "cbId": 15708 }, { "Id": 15393, "fn": "Fakhar Zaman", "n": "Fakhar Zaman", "nn": "", "bts": false, "bs": "", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 10863 }, { "Id": 18760, "fn": "Haris Rauf", "n": "Haris Rauf", "nn": "", "bts": false, "bs": "", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 14561 }, { "Id": 15877, "fn": "Jaahid Ali", "n": "Jaahid Ali", "nn": "", "bts": false, "bs": "", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 8365 }, { "Id": 12292, "fn": "Lendl Mark Platter Simmons", "n": "Lendl Simmons", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 599 }, { "Id": 13050, "fn": "Mohammad Hafeez", "n": "Mohammad Hafeez", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 360 }, { "Id": 13055, "fn": "Salman Butt", "n": "Salman Butt", "nn": "", "bts": false, "bs": "Left-hand bat", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 143 }, { "Id": 11234, "fn": "Samit Rohit Patel", "n": "Samit Patel", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 1414 }, { "Id": 13217, "fn": "Seekkuge Prasanna", "n": "Seekkuge Prasanna", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 0 }, { "Id": 15827, "fn": "Shaheen Afridi", "n": "Shaheen Afridi", "nn": "", "bts": false, "bs": "", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 12160 }, { "Id": 15908, "fn": "Sohail Akhtar", "n": "Sohail Akhtar", "nn": "", "bts": false, "bs": "", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 13623 }, { "Id": 14181, "fn": "Usman Khan Shinwari", "n": "Usman Shinwari", "nn": "", "bts": false, "bs": "Bowler", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 9698 }, { "Id": 23726, "fn": "Mohammad Faizan", "n": "Mohammad Faizan", "nn": "", "bts": false, "bs": "", "d": "", "un": "", "ine": false, "tids": null, "cbId": 0 }, { "Id": 23727, "fn": "Farzan Raja", "n": "Farzan Raja", "nn": "", "bts": false, "bs": "", "d": "", "un": "", "ine": false, "tids": null, "cbId": 0 }];
export const KK = [{ "Id": 13732, "fn": "Aamer Yamin", "n": "Aamer Yamin", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 10618 }, { "Id": 11252, "fn": "Alexander Daniel Hales", "n": "Alex Hales", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 6734 }, { "Id": 13026, "fn": "Arshad Khan", "n": "Arshad Khan", "nn": "", "bts": true, "bs": "Right-arm offbreak", "d": "", "un": "", "ine": false, "tids": null, "cbId": 369 }, { "Id": 14179, "fn": "Awais Zia", "n": "Awais Zia", "nn": "", "bts": false, "bs": "Left-hand bat", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 8249 }, { "Id": 13099, "fn": "Mohammad Babar Azam", "n": "Babar Azam", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 8359 }, { "Id": 15397, "fn": "Cameron Delport", "n": "Cameron Delport", "nn": "", "bts": false, "bs": "", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 9719 }, { "Id": 11246, "fn": "Christopher James Jordan", "n": "Chris Jordan", "nn": "", "bts": false, "bs": "Bowler", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 6532 }, { "Id": 20521, "fn": "Dan Lawrence", "n": "Dan Lawrence", "nn": "", "bts": false, "bs": "", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 10385 }, { "Id": 13098, "fn": "Iftikhar Ahmed", "n": "Iftikhar Ahmed", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 10799 }, { "Id": 13731, "fn": "Syed Imad Wasim", "n": "Imad Wasim", "nn": "", "bts": false, "bs": "Left-hand bat", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 10408 }, { "Id": 11211, "fn": "Liam Edward Plunkett", "n": "Liam Plunkett", "nn": "", "bts": false, "bs": "Bowler", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 479 }, { "Id": 13071, "fn": "Mohammad Amir", "n": "Mohammad Amir", "nn": "", "bts": false, "bs": "Bowler", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 1917 }, { "Id": 13729, "fn": "Mohammad Rizwan", "n": "Mohammad Rizwan", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 9468 }, { "Id": 13727, "fn": "Sharjeel Khan", "n": "Sharjeel Khan", "nn": "", "bts": false, "bs": "Left-hand bat", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 9052 }, { "Id": 15916, "fn": "Umaid Asif", "n": "Umaid Asif", "nn": "", "bts": false, "bs": "", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 8581 }, { "Id": 18832, "fn": "Umer Khan", "n": "Umer Khan", "nn": "", "bts": false, "bs": "", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 12161 }, { "Id": 14233, "fn": "Usama Mir", "n": "Usama Mir", "nn": "", "bts": false, "bs": "", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 11318 }, { "Id": 15779, "fn": "Muhammad Ashan Ali Khan", "n": "Ali Khan", "nn": "", "bts": false, "bs": "", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 11450 }];
export const IU = [{ "Id": 19300, "fn": "Akif Javed", "n": "Akif Javed", "nn": "", "bts": false, "bs": "", "d": "", "un": "", "ine": false, "tids": null, "cbId": 0 }, { "Id": 15388, "fn": "Amad Butt", "n": "Amad Butt", "nn": "", "bts": false, "bs": "", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 9902 }, { "Id": 15386, "fn": "Asif Ali", "n": "Asif Ali", "nn": "", "bts": false, "bs": "", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 9565 }, { "Id": 13533, "fn": "Colin Alexander Ingram", "n": "Colin Ingram", "nn": "", "bts": false, "bs": "Top-order batsman", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 7664 }, { "Id": 12585, "fn": "Colin Munro", "n": "Colin Munro", "nn": "", "bts": false, "bs": "Left-hand bat", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 8085 }, { "Id": 11992, "fn": "Dale Willem Steyn", "n": "Dale Steyn", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 508 }, { "Id": 15633, "fn": "Fahim Ashraf", "n": "Faheem Ashraf", "nn": "", "bts": false, "bs": "", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 11265 }, { "Id": 15387, "fn": "Hussain Talat", "n": "Hussain Talat", "nn": "", "bts": false, "bs": "", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 9804 }, { "Id": 12594, "fn": "Luke Ronchi", "n": "Luke Ronchi", "nn": "", "bts": false, "bs": "Wicketkeeper batsman", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 1396 }, { "Id": 15970, "fn": "Muhammad Musa", "n": "Muhammad Musa", "nn": "", "bts": false, "bs": "", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 12156 }, { "Id": 18690, "fn": "Philip Salt", "n": "Philip Salt", "nn": "", "bts": false, "bs": "", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 10479 }, { "Id": 17368, "fn": "Hendrik Erasmus van der Dussen", "n": "Rassie van der Dussen", "nn": "", "bts": false, "bs": "", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 9554 }, { "Id": 17306, "fn": "Rizwan Hussain", "n": "Rizwan Hussain", "nn": "", "bts": false, "bs": "", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 14562 }, { "Id": 14186, "fn": "Rumman Raees Khan", "n": "Rumman Raees", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 10861 }, { "Id": 15408, "fn": "Saif Badar", "n": "Saif Badar", "nn": "", "bts": false, "bs": "", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 11192 }, { "Id": 15390, "fn": "Shadab Khan", "n": "Shadab Khan", "nn": "", "bts": false, "bs": "", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 11186 }, { "Id": 13734, "fn": "Zafar Gohar Khan", "n": "Zafar Gohar", "nn": "", "bts": false, "bs": "Left-hand bat", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 8567 }, { "Id": 23725, "fn": "Ahmed Safi Abdullah", "n": "Ahmed Safi Abdullah", "nn": "", "bts": false, "bs": "", "d": "", "un": "", "ine": false, "tids": null, "cbId": 0 }];
export const QG = [{ "Id": 19010, "fn": "Aarish Ali Khan", "n": "Aarish Ali Khan", "nn": "", "bts": false, "bs": "", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 0 }, { "Id": 13093, "fn": "Ahmed Shehzad", "n": "Ahmed Shehzad", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 1787 }, { "Id": 15457, "fn": "Ahsan Ali", "n": "Ahsan Ali", "nn": "", "bts": false, "bs": "", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 12702 }, { "Id": 13015, "fn": "Mohammad Azam Khan", "n": "Azam Khan", "nn": "", "bts": true, "bs": "", "d": "", "un": "", "ine": false, "tids": null, "cbId": 3747 }, { "Id": 13493, "fn": "Benjamin Colin James Cutting", "n": "Ben Cutting", "nn": "", "bts": false, "bs": "Allrounder", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 8118 }, { "Id": 13495, "fn": "Fawad Ahmed", "n": "Fawad Ahmed", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 8969 }, { "Id": 13460, "fn": "Jason Jonathan Roy", "n": "Jason Roy", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 6534 }, { "Id": 15809, "fn": "Keemo Paul", "n": "Keemo Paul", "nn": "", "bts": false, "bs": "", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 11214 }, { "Id": 13067, "fn": "Khurram Manzoor", "n": "Khurram Manzoor", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 1044 }, { "Id": 18852, "fn": "Mohammad Hasnain", "n": "Mohammad Hasnain", "nn": "", "bts": false, "bs": "", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 14248 }, { "Id": 13100, "fn": "Mohammad Nawaz", "n": "Mohammad Nawaz", "nn": "", "bts": false, "bs": "Left-hand bat", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 8367 }, { "Id": 18761, "fn": "Naseem Shah", "n": "Naseem Shah", "nn": "", "bts": false, "bs": "", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 14247 }, { "Id": 13075, "fn": "Sarfraz Ahmed", "n": "Sarfaraz Ahmed", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 881 }, { "Id": 11643, "fn": "Shane Robert Watson", "n": "Shane Watson", "nn": "", "bts": false, "bs": "Allrounder", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 158 }, { "Id": 13068, "fn": "Sohail Khan", "n": "Sohail Khan", "nn": "", "bts": false, "bs": "Bowler", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 1120 }, { "Id": 14137, "fn": "Tymal Solomon Mills", "n": "Tymal Mills", "nn": "", "bts": true, "bs": "Left-arm fast", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 7860 }, { "Id": 13074, "fn": "Umar Akmal", "n": "Umar Akmal", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 1992 }, { "Id": 23724, "fn": "Abdul Nasir", "n": "Abdul Nasir", "nn": "", "bts": false, "bs": "", "d": "", "un": "", "ine": false, "tids": null, "cbId": 0 }];
export const MS = [{ "Id": 12005, "fn": "Mohammad Imran Tahir", "n": "Imran Tahir", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 6667 }, { "Id": 13085, "fn": "Mohammad Junaid Khan", "n": "Junaid Khan", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 7900 }, { "Id": 13089, "fn": "Mohammad Irfan", "n": "Muhammad Irfan", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 7621 }, { "Id": 13091, "fn": "Shan Masood Khan", "n": "Shan Masood", "nn": "", "bts": false, "bs": "Shaani", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 9545 }, { "Id": 13065, "fn": "Sohail Tanvir", "n": "Sohail Tanvir", "nn": "", "bts": false, "bs": "Left-hand bat", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 859 }, { "Id": 18786, "fn": "Mohammad Ilyas", "n": "Mohammad Ilyas", "nn": "", "bts": false, "bs": "", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 12714 }, { "Id": 13030, "fn": "Sahibzada Mohammad Shahid Khan Afridi", "n": "Shahid Afridi", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "All Rounder", "un": "شاہد آفریدی", "ine": false, "tids": null, "cbId": 142 }, { "Id": 15924, "fn": "Ali Shafiq", "n": "Ali Shafiq", "nn": "", "bts": false, "bs": "", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 14359 }, { "Id": 11253, "fn": "James Michael Vince", "n": "James Vince", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 6642 }, { "Id": 11245, "fn": "Moeen Munir Ali", "n": "Moeen Ali", "nn": "", "bts": false, "bs": "Batting allrounder", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 6692 }, { "Id": 13538, "fn": "Rilee Roscoe Rossouw", "n": "Rilee Rossouw", "nn": "", "bts": false, "bs": "Left-hand bat", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 2244 }, { "Id": 18893, "fn": "Zeeshan Ashraf", "n": "Zeeshan Ashraf", "nn": "", "bts": false, "bs": "", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 0 }, { "Id": 11220, "fn": "Ravinder Singh Bopara", "n": "Ravi Bopara", "nn": "", "bts": false, "bs": "Middle-order batsman", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 571 }, { "Id": 15403, "fn": "Khushdil Shah", "n": "Khushdil Shah", "nn": "", "bts": false, "bs": "", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 12565 }, { "Id": 15402, "fn": "Usman Qadir", "n": "Usman Qadir", "nn": "", "bts": false, "bs": "", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 8373 }, { "Id": 15795, "fn": "Fabian Allen", "n": "Fabian Allen", "nn": "", "bts": false, "bs": "", "d": "All Rounder", "un": "", "ine": false, "tids": null, "cbId": 9785 }, { "Id": 15902, "fn": "Rohail Nazir", "n": "Rohail Nazir", "nn": "", "bts": false, "bs": "", "d": "Batsman", "un": "", "ine": false, "tids": null, "cbId": 13192 }, { "Id": 13094, "fn": "Bilawal Bhatti", "n": "Bilawal Bhatti", "nn": "", "bts": false, "bs": "Right-hand bat", "d": "Bowler", "un": "", "ine": false, "tids": null, "cbId": 8582 }];